"""Add name field to User model

Revision ID: 67120c3a7ae5
Revises: eba8e5a58864
Create Date: 2023-12-18 23:18:27.313465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67120c3a7ae5'
down_revision = 'eba8e5a58864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
